---
- name : win_chocolatey module demo
  hosts: windows-servers
  become: false
  gather_facts: false
  vars:
    - packages:
      -notepadplusplus
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
         present

